name = "omi-assist-api"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"

[env.prod]
build = { command = "worker-build --release" }
d1_databases = [{ binding = "DB-omi-assist", database_name = "omi-assist", database_id = "3bc8bb8f-87f6-4814-b021-d83c908b0e45", migrations_dir = "../db/migrations" }]
kv_namespaces = [
  { binding = "KV-omi-auth-token-signin", id = "2d70def966254096bee7d629be6fb766" }
]

[env.dev]
build = { command = "worker-build --dev" }
d1_databases = [{ binding = "DB-omi-assist", database_name = "omi-assist", database_id = "3bc8bb8f-87f6-4814-b021-d83c908b0e45", migrations_dir = "../db/migrations" }]
kv_namespaces = [
  { binding = "KV-omi-auth-token-signin", id = "2d70def966254096bee7d629be6fb766" }
]

[[migrations]]
tag = "v1"

[observability]
enabled = true
logs = {enabled = true}